# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-08-31 14:44:12
"""
import arcpy
from sys import argv

def Model21(districts001_2_="districts001"):  # Polsby Popper

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx.tbx")

    # Process: Add Geometry Attributes (Add Geometry Attributes) (management)
    districts001_4_ = arcpy.management.AddGeometryAttributes(Input_Features=districts001_2_, Geometry_Properties=["AREA_GEODESIC"], Length_Unit="METERS", Area_Unit="", Coordinate_System="")[0]

    # Process: Add Geometry Attributes (2) (Add Geometry Attributes) (management)
    districts001_6_ = arcpy.management.AddGeometryAttributes(Input_Features=districts001_4_, Geometry_Properties=["PERIMETER_LENGTH_GEODESIC"], Length_Unit="METERS", Area_Unit="", Coordinate_System="")[0]

    # Process: Calculate Field (Calculate Field) (management)
    districts001_3_ = arcpy.management.CalculateField(in_table=districts001_6_, field="Polsby", expression="(4 * math.pi * !AREA_GEO!) / (!PERIM_GEO! * !PERIM_GEO!)", expression_type="PYTHON3", code_block="", field_type="DOUBLE", enforce_domains="NO_ENFORCE_DOMAINS")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"c:\research.gdb", workspace=r"c:\summer_research.gdb"):
        Model21(*argv[1:])
